### PR TITLE
feat(jessieOverrides): simpler .eslintrc.js API

### PR DESCRIPTION
**Pull request by michaelfig**
This new function encapsulates more of the Jessie detection in
order to make .eslintrc.js files simpler.

Update README accordingly.

### CODE REVIEW

**Comment by katelynsills** [comment]
Should I make another release after this is in?

**Comment by erights** [comment]
Could we also have some file with the "use jessie" directive so that the mechanism is engaged in at least one case?

**Comment by michaelfig** [comment]
I'll write some tests.

**Comment by michaelfig** [comment]
Turns out it's *really* hard to write tests that don't trigger eslint warnings in the same repo.  I'm merging this for now, in the hopes of writing tests in some better future world.

**Pull request merged**
